version: '3.8'
services:
  postgres-dev:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: elearning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: elearning-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
